### ISSUE TITLE
没网络下，运行npx wasm4 run snake.wasm 卡死

### ISSUE THREAD

**Issue by retfings** [moonbitlang/wasm4#7]
您好，最近在参加社区的比赛（游戏开发挑战赛道）。
本地有一个snake.wasm文件，在没有网络的环境下运行 `npx wasm4 run snake.wasm `**命令会出现卡死情况**。
连上网络之后就可以执行了，由于网络波动的原因，长长出现断网情况，希望能够离线条件下能够执行`npx wasm4 run`

**Comment by peter-jerry-ye** [comment]
未能复现。如果你本地先执行`npm install -D wasm4`是否还会出现问题？
